---
title: "dd"
author: "202021540 박유선"
date: '2021 6 20 '
output: html_document
---

```{r}
apt<- read.csv("apt_final_1.csv")
table(apt$지역)

c.apt<- mean(apt$범죄발생수)
apt[apt$범죄발생수 < c.apt, "범죄발생수"] = "1"
apt[apt$범죄발생수 >= c.apt, "범죄발생수"] = "2"

h.apt<- mean(apt$보건기관수)
apt[apt$보건기관수 < h.apt, "보건기관수"] = "1"
apt[apt$보건기관수 >= h.apt, "보건기관수"] = "2"

e.apt<- mean(apt$교육기관수)
apt[apt$교육기관수 < e.apt, "교육기관수"] = "1"
apt[apt$교육기관수 >= e.apt, "교육기관수"] = "2"

n.apt<- mean(apt$유흥업소수)
apt[apt$유흥업소수< n.apt, "유흥업소수"] = "1"
apt[apt$유흥업소수>= n.apt, "유흥업소수"] = "2"

p.apt<- mean(apt$국립공원수)
apt[apt$국립공원수< p.apt, "국립공원수"] = "1"
apt[apt$국립공원수>= p.apt, "국립공원수"] = "2"

t.apt<- mean(apt$해당.지역.지하철.지점수)
apt[apt$해당.지역.지하철.지점수< t.apt, "해당.지역.지하철.지점수"] = "1"
apt[apt$해당.지역.지하철.지점수>= t.apt, "해당.지역.지하철.지점수"] = "2"

apt[, 12:17] = lapply(apt[,12:17], factor)

str(apt)

table(apt$국립공원수)

boxplot(apt$평당가격)$stats

apt$평당가격<- ifelse(apt$평당가격 < 461 | apt$평당가격 > 7955, NA, apt$평당가격)
sum(is.na(apt))
apt<- na.omit(apt)

write.csv(apt, "rn_apt_factor.csv")
```

```{r}
```

