
```{r}
apt<- read.csv("apt_final_1.csv")

apt_1<- aggregate(평당가격~지역+ 범죄발생수+보건기관수+교육기관수+유흥업소수+국립공원수+해당.지역.지하철.지점수, apt, mean)

write.csv(apt_1, "gu_data.csv")
```

```{r}
gu<- read.csv("gu_data.csv")
library<- read.csv("서울시 공공도서관.csv")
passport<- read.csv("서울시 여권 발급.csv")
car<- read.csv("서울시 자동차 등록.csv")

car<- car[-1,c(2,5)]
library<- library[,c(2,5,8)]
passport<- passport[-1,2:3]

library(dplyr)

car<- rename(car, 지역 = 자치구)
library<- rename(library, 지역 = 자치구)
passport<- rename(passport, 지역 = 자치구)


merge1<- merge(gu, car, by = "지역")
merge2<- merge(merge1, library, by="지역")
merge3<- merge(merge2, passport, by="지역")

str(merge3)
merge3<- rename(merge3, 여권발급합계= 합계)
merge3<- rename(merge3, 보유도서합계 = 도서)

merge3<- merge3[,-2]

merge3[,9]<-gsub(",", "", merge3[,9])
merge3[,10]<-gsub(",", "", merge3[,10])
merge3[,11]<-gsub(",", "", merge3[,11])
merge3[,12]<-gsub(",", "", merge3[,12])

merge3[,9]<-as.numeric(merge3[,9])
merge3[,10]<-as.numeric(merge3[,10])
merge3[,11]<-as.numeric(merge3[,11])
merge3[,12]<-as.numeric(merge3[,12])

write.csv(merge3, "gu_data_2.csv")
```

