
## 7. 주성분 분석
### 7.1. 전처리
```{r}
gu<- read.csv("gu_data_3.csv")
price<- gu$평당가격

# 주성분 분석을 위한 전처리
rownames(gu)<- gu$지역

# 변수로 필요한 열만 추출해 log 취함.
apt_pca<- log(gu[,c(-1,-2,-12)])
```

### 7.2. 주성분 분석
```{r}
pca.out<-prcomp(apt_pca, scale. = T)

biplot(pca.out) # 그래프로 축과 데이터 확인
screeplot(pca.out, type = "l") # 성분 개수 선택을 위한 그래프 확인
summary(pca.out) # 정확한 값으로 확인
pca.out
```

```
** PCA 결과 분석
그래프를 보면 1에서 3까지는 정보량을 어느정도 가지고 있지만 4부터는 매우 적어지는 것을 알 수 있다.  
더 자세한 값을 확인해보면 PC1: 0.3685 0.1910 0.1105 0.1036 0.06944라는 결과가 나왔다.  
따라서, PC3까지 포함해 3개의 성분으로 전체 분산의 81.44%를 설명하는 것을 선택하기로 했다.  
PCA 결과에 따르면, 스케일된 값이라 하나의 값이 PCA의 결과를 좌우하는 상황은 보이지 않는다.
```


### 7.3. 기본 회귀모델과 주성분 분석 결과에 따른 회귀모델 성능 비교
#### 7.3.1. 기본회귀모델의 RMSE 구하기
```{r}
# 기본모델
og.model<- lm(평당가격 ~ 해당.지역.지하철.지점수 + 유흥업소수 + 보건기관수 + 도서관.방문자수 + 여권발급합계, data = gu)

# 기본 회귀모델의test, train set
train.og<- gu[1:16, c(4,6,8,9,12,13)]
test.og<-gu[17:24, c(4,6,8,9,12,13)]
test.og.y<- price[17:24]

# 예측모델
og.pred<- predict(og.model, newdata = train.og)

# RMSE
sqrt(mean((og.pred - test.og.y)^2))
```

#### 7.3.2. 주성분 분석 결과에 따른 회귀모델의 RMSE 구하기
```{r}
# 전처리
prc <- as.matrix(apt_pca) %*% pca.out$rotation
bind.price<- cbind(price, as.data.frame(prc))

# train, test set
train.prc<- bind.price[1:16,]
test.prc<- bind.price[17:24,]
test.prc.y<- price[17:24]

# 회귀모델
prc.model <- lm(price~PC1+PC2+PC3, data = train.prc)

# 예측모델
pcr.pred<- predict(prc.model, newdata = test.prc)

# RMSE
sqrt(mean((pcr.pred - test.prc.y)^2))
```

설명|기본 모델|주성분 분석 결과에 따른 회귀모델
-----|----------|--------
독립변수의 개수|5개|3개
RMSE|128.9325|120.7944


```
주성분 분석 결과에 따른 모델을 만들어 평균 제곱근 오차를 계산한 결과 120.7944가 나온다. 기본 회귀모델의 결과인 128.9325보다 8 정도 줄어들었다. 기본 회귀모델은 5개의 독립변수(전철역의 수, 유흥업소 수, 보건기관 수, 도서관 방문자 수, 여권발급 수)로 평균 제곱근 오차가 128.9325가 나왔다. 반면에, 주성분 분석 결과에 따라 3개로 줄인 회귀모델은 평균 제곱근 오차가 120.7944가 나왔다.  
따라서, 새로 만든 모델이 더 적은 수의 변수로 원본과의 오차가 더 적게 나타나기 떄문에 추측한 값의 정확성이 더 높게 나타남을 알 수 있다.
```